### ISSUE TITLE
Next.js throws when pre-rendering: TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by amar-mesic** [cookpete/react-player#1611]
#### Current Behavior
When trying to add the <ReactPlayer /> component into my Server-side rendered (pre-rendered) page in Next.js, it throws a ServerError. It happens whether or not I have only set the url or other props as well. The error does not occur if I import and do not use the component, only when the component is used. The error does not occur if I make my page render client-side, but for performance reasons I really want to have the page be pre-rendered.

My page: mission.tsx
`
import ReactPlayer from 'react-player'

export const MissionSlice = async (props) => {

  return (
    <ReactPlayer url={"https://www.youtube.com/watch?v=Et7TTfwvBFo"} />
  );
};
`

Error Call stack:
`
at _inherits (webpack-internal:///(sc_server)/../../node_modules/react-player/lib/Player.js:102:15)
at eval (webpack-internal:///(sc_server)/../../node_modules/react-player/lib/Player.js:177:5)
at eval (webpack-internal:///(sc_server)/../../node_modules/react-player/lib/Player.js:453:2)
at (sc_server)/../../node_modules/react-player/lib/Player.js (file:///Users/.../colecto-frontend/apps/web/.next/server/app/(user)/[slug]/page.js:9963:1)
at __webpack_require__ (/Users/.../colecto-frontend/apps/web/.next/server/webpack-runtime.js:33:43)
at eval (webpack-internal:///(sc_server)/../../node_modules/react-player/lib/ReactPlayer.js:12:39)
at (sc_server)/../../node_modules/react-player/lib/ReactPlayer.js (file:///Users/.../colecto-frontend/apps/web/.next/server/app/(user)/[slug]/page.js:9985:1)
at __webpack_require__ (/Users/.../colecto-frontend/apps/web/.next/server/webpack-runtime.js:33:43)
at eval (webpack-internal:///(sc_server)/../../node_modules/react-player/lib/index.js:7:20)
at (sc_server)/../../node_modules/react-player/lib/index.js (file:///Users/.../colecto-frontend/apps/web/.next/server/app/(user)/[slug]/page.js:9996:1)
`

What could be preventing this from working server-side?

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=Et7TTfwvBFo
- Browser: Brave Browser
- Operating system: Mac OS 13.2.1
- React: ^18
- next: ^13.2.4
- next-sanity: 4.1.5
- sanity/client: 5.2.2

#### Other Information
This is on a sanity project using Next.js, in this specific context making a slice. Switching over to "use client" with a sync component works.

**Comment by lucasbento** [comment]
Duplicated #1565.

Nonetheless, this fixed it for me (even though there were a few errors in the console): https://github.com/cookpete/react-player/issues/1565#issuecomment-1417956015.
