### ISSUE TITLE
Failed to resolve entry for package "load-script".

### ISSUE THREAD

**Issue by ExorTek** [cookpete/react-player#1724]
##The problem I experienced during the build
### Error
```bash[commonjs--resolver] Failed to resolve entry for package "load-script". The package may have incorrect main/module/exports specified in its package.json.
file: /home/project/node_modules/react-player/lib/index.js
error during build:
Error: Failed to resolve entry for package "load-script". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///home/project/node_modules/vite/dist/node/chunks/dep-MF_y65BT.js:29087:17)
    at resolvePackageEntry (file:///home/project/node_modules/vite/dist/node/chunks/dep-MF_y65BT.js:29084:5)
    at tryNodeResolve (file:///home/project/node_modules/vite/dist/node/chunks/dep-MF_y65BT.js:28854:20)
    at Object.resolveId (file:///home/project/node_modules/vite/dist/node/chunks/dep-MF_y65BT.js:28610:28)
    at file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:18606:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/projectnew/node_modules/rollup/dist/es/shared/node-entry.js:18506:28)
    at async resolveId (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:17175:26)
    at async ModuleLoader.resolveId (file:///home/project/node_modules/rollup/dist/es/shared/nodeentry.js:17589:15)
    at async file:///home/project/node_modules/vite/dist/node/chunks/dep-MF_y65BT.js:8338:16
    at async Promise.all (index 0)
```

### Env
Node version: v20.10.0
Vite : 5.0.10
React Player : 2.14.1
React: 18.2.0
OS: Ubuntu: 20.04

**Comment by ExorTek** [comment]
I used it in two different places

```jsx
   <ReactPlayer
      playing={true}
      url={'/play/map.mp4'}
      muted
      width={'100%'}
      height={'100%'}
      controls={false}
      loop
     />
```

```jsx
  <ReactPlayer
    url={ytUrl}
    controls={true}
    width={'60%'}
    height={'70%'}
    volume={0.1}
    config={{
     file: {
      attributes: {
       controlsList: 'nodownload',
      },
     },
    }}
   />
```

**Comment by ExorTek** [comment]
When I tried again on another remote server, it worked. This time, I was able to build strangely. @luwes

**Comment by ExorTek** [comment]
I think it gives this error when you use low volume CPU or RAM.

**Comment by luwes** [comment]
thanks for letting us know!

**Comment by ExorTek** [comment]
Now I rebuilt it on a server with low volume CPU and RAM and it worked strangely, I guess it has nothing to do with that either
