### ISSUE TITLE
TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by asbetter** [CookPete/react-player#430]
Hi Peter,

Compliments for the player, nice work!

I am using react-player inside my react component but getting the following error while running jest tests: 

TypeError: Cannot read property 'addEventListener' of null

at FilePlayer.addListeners (node_modules/react-player/lib/players/FilePlayer.js:144:19)
at FilePlayer.componentDidMount (node_modules/react-player/lib/players/FilePlayer.js:109:12)
....

Any ideas?

Thanks!

**Comment by CookPete** [comment]
See #427. You need to mock the `window` global when testing FilePlayer.
